<a href="https://colab.research.google.com/github/Oumayma-Jribi/github-slideshow/blob/my-slide/Numpy_first_trial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
first_array = np.array([1,2,3])
print(first_array)

[1 2 3]


In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

np.arange includes lower bound but not the upper bound

In [10]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [11]:
np.random.randint(low=50, high=101, size=(6))

array([79, 90, 66, 62, 84, 97])

random numbers between 0 and 1

In [14]:
np.random.random([3])+2

array([2.55726042, 2.7522868 , 2.33854649])